### ISSUE TITLE
FR: Make configs writable

### ISSUE THREAD

**Issue by alippert** [kyrofa/nextcloud-snap#16]
Current snap writes app configs to non-writeable file system - tough to customize the installation. Would love to see configs that are writable. Perhaps a snap that installs and configure the dependencies as non-writable, but htdocs as writable?

**Comment by nidusin** [comment]
This would be very useful to allow for things like trusted domains to be updated.

**Comment by kyrofa** [comment]
> This would be very useful to allow for things like trusted domains to be updated.

That's already possible-- the Nextcloud config is certainly writable (Nextcloud's usability is quite limited without this).

What configs are we talking about?

**Comment by nidusin** [comment]
Thanks kyrofa.  My personal issue was that nextcloud was not responding to a dynamic DNS host name allocation and I was attempting to add this domain to a config.php file somewhere. I thought the snap setup must have been the issue but your comment makes me think I was just looking in the wrong place. I appreciate all the work you've put into it!

**Comment by kyrofa** [comment]
> Thanks kyrofa. My personal issue was that nextcloud was not responding to a dynamic DNS host name allocation and I was attempting to add this domain to a config.php file somewhere.

If it's reachable via that domain you should have seen a "this isn't a trusted domain, login if you want to add it" kind of page. If you didn't see that something else is wrong. Note that you can alter the config via `sudo /snap/bin/nextcloud.occ` (/snap/bin isn't in sudo's path, it's a bug).

**Comment by nidusin** [comment]
> Note that you can alter the config via sudo /snap/bin/nextcloud.occ
Excellent. I'll familiarise myself with it and see what I can find. Thanks again.

**Comment by kyrofa** [comment]
I'm going to go ahead and close this since I think it was a misunderstanding. Please reopen if that's not the case.

**Comment by laurentdinclaux** [comment]
Is httpd.conf writable ? I want to change the port.
