### ISSUE TITLE
Enable memcache

### ISSUE THREAD

**Issue by Teuwu** [kyrofa/nextcloud-snap#2]
Upon visiting the admin page after initial install, says that there is no memcache installed.

**Comment by kyrofa** [comment]
Thanks @Teuwu, glad you enjoyed the experience! I also appreciate your logging the issue.

Indeed, there is no memcache configured right now, but I'll incorporate one soon. Probably redis.

For HTTPS I plan on using Let's Encrypt, but I'd like to make it very user-friendly... maybe some sort of first-use wizard, or a Nextcloud plugin. It requires some investigation.

**Comment by kyrofa** [comment]
I'm going to split this into two issues, one for the memcache and the other for HTTPS.
